name: Test on AI21

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: echo 'Which planet in our solar system is the largest?' | ./ask-llm.js | tee output.txt | grep -i jupiter
        timeout-minutes: 3
        env:
          LLM_API_BASE_URL: 'https://api.ai21.com/studio/v1'
          LLM_API_KEY: ${{ secrets.AI21_API_KEY }}
          LLM_CHAT_MODEL: 'jamba-1.5-mini'

      - run: cat output.txt
